### ISSUE TITLE
Build failed on MacOS

### ISSUE THREAD

**Issue by higumachan** [twistedfall/opencv-rust#129]
Hi I met build error on Mac OS.
I looks some problem about LLVM.
I want to help.

These are my scenario.

item | desc
-- | --
OS | MacOS 10.14.6
OpenCV 4 directory |  /usr/local/Cellar/opencv/4.3.0
opencv-rust features | buildtime-bindgen,contrib
How to install Opencv | brew install opencv
llvm directory | /usr/local/Cellar/llvm/7.0.1/

And, this is a my build log.

[fail.log](https://github.com/twistedfall/opencv-rust/files/4643713/fail.log)

thanks.

**Comment by twistedfall** [comment]
Are you using `clang_sys` with `runtime` feature enabled somewhere in your Cargo.toml or dependencies? That combination wasn't working for me in multithreaded generation so it's known to be broken at the moment.

**Comment by higumachan** [comment]
Thank you for response.

I look there doesn't seem to be a clang_sys with "runtime" feature dependency.

these are Cargo.toml files by I wrote.

```toml
[package]
name = "dobot-rs"
version = "0.1.0"
authors = ["higumachan <harekumo792154@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

members = [
    "libdobot",
]

[dependencies]
libdobot = { path = "./libdobot" }
opencv = {version = "0.36", features = ["buildtime-bindgen"]}
tokio = { version = "0.2.21", features = ["full"] }
```

```toml
[package]
name = "libdobot"
version = "0.1.0"
authors = ["higumachan <harekumo792154@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "^0.53"
cmake = "0.1"

[dependencies]
strum = "^0.18"
strum_macros = "^0.18"
tokio = { version = "^0.2", features = ["time"] }
```

**Comment by twistedfall** [comment]
Ah, it's `bindgen`, from [its Cargo.toml](https://github.com/rust-lang/rust-bindgen/blob/master/Cargo.toml):
```
[features]
default = [... "runtime" ...]
runtime = ["clang-sys/runtime"]
```
I'll see what can be done, but in the meanwhile you can do a quick fix, in the `build.rs` change line:
```rust
modules.par_iter().for_each(|module| {
```
to read:
```rust
modules.iter().for_each(|module| {
```
and in the `binding-generator/Cargo.toml` make the lines read:
```toml
clang = {version = "0.23", features = ["runtime", "clang_6_0"]}
clang-sys = {version = "0.28", features = ["runtime", "clang_6_0"]}
```
The build will be slower, but it should get past the generation phase.
