### ISSUE TITLE
Failed to build clang-sys

### ISSUE THREAD

**Issue by Jesse-Millwood** [twistedfall/opencv-rust#318]
I have a very sparse build so far. 
Here is my Cargo.toml: 

```toml
[package]
name = "opencv-project"
version = "0.1.0"
authors = ["Jesse <me@email.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.62"

```

My `lib.rs` just contains this so far: 

```rust
use opencv::{
    prelude::*,
    highgui,
    imgcodecs,
    Result,

};

fn main() -> Result<()> {
    let image = imgcodecs::imread("lena.jpg", 0)?;
    highgui::named_window("hello opencv!", 0)?;
    highgui::imshow("hello opencv!", &image)?;
    highgui::wait_key(10000)?;
    Ok(())
}

```

This seems like more of an issue with libclang-sys. Is there a way I can specify a working version of libclang-sys? It looks a like a new version. Is there a known version that works with opencv-rust?

Here is the requested info:

1. Operating system
Pop!_OS 21.10
2. The way you installed OpenCV: package, official binary distribution, manual compilation, etc.
`apt install opencv-dev`
3. OpenCV version
4.5.3
4. rustc version (`rustc --version`)
1.58.1
5. Attach the full output of the following command from your project directory:
   ```shell script
   [build.log](https://github.com/twistedfall/opencv-rust/files/7964192/build.log)
   ```
