### ISSUE TITLE
Cross compiling to arm linux platform : Segmentation fault (core dumped)  

### ISSUE THREAD

**Issue by kingzcheung** [twistedfall/opencv-rust#336]
I am doing cross compiling to arm linux platform.
 I don't need these modules like viz, sfm,freetype etc.
 But now I have to add these so libraries to compile.

![image](https://user-images.githubusercontent.com/12839855/164970897-74821856-830d-4fc3-a645-bd69b168f1a5.png)
![image](https://user-images.githubusercontent.com/12839855/164970928-9e7b0d4f-26c3-449e-b186-7b4b0f279490.png)

My dependencies:

```toml
[dependencies]
opencv = {version="0.63", default-features = false, features = [ "imgcodecs","videoio","highgui"]}

```
