### ISSUE TITLE
CI problem with GH actions and macOS

### ISSUE THREAD

**Issue by neilyoung** [twistedfall/opencv-rust#343]
You recommend to set `DYLD_FALLBACK_LIBRARY_PATH`

https://github.com/twistedfall/opencv-rust#:~:text=On%20macOS%20you%27re,xctoolchain/usr/lib/%22

Unfortunately Apple's System Integrity Protection disallows to set this environment variable and Github's images don't disable SIP.

Refer to:

https://apple.stackexchange.com/questions/212945/unable-to-set-dyld-fallback-library-path-in-shell-on-osx-10-11-1
https://github.com/actions/virtual-environments/issues/650

Please also check this little GH script:

```yaml
name: Test

on:
  workflow_dispatch

jobs:
  test_job:
    runs-on: macos-latest
    steps:
      - name: Test
        run: |
          echo "PATHX=$(xcode-select --print-path)/Toolchains/XcodeDefault.xctoolchain/usr/lib/" >> $GITHUB_ENV
          
      - name: Test
        run: |
          echo "DYLD_FALLBACK_LIBRARY_PATH=$PATHX" >> $GITHUB_ENV
      

      - name: Test
        run: |
          echo ${PATHX:-is_empty}
          echo ${DYLD_FALLBACK_LIBRARY_PATH:-is_empty}
         
```

The DYLD_FALLBACK_LIBRARY_PATH variable is always empty, even set correctly.

Would there be another way to satisfy the requirement of providing the lib path to the compiler?
