### ISSUE TITLE
macOS, fatal error: 'memory' file not found

### ISSUE THREAD

**Issue by fbuedding** [twistedfall/opencv-rust#623]
Can't build.
Also ran `clang -E -x c++ - -v`, `lib` directory under `include <...>` includes memory.h

1. Operating system:
```
ProductName:            macOS
ProductVersion:         15.0.1
BuildVersion:           24A348
```
3. The way you installed OpenCV:` package, brew`
5. OpenCV version: `opencv: stable 4.10.0 (bottled), HEAD`
6. rustc version `rustc 1.81.0 (eeb90cda1 2024-09-04)`
7. Attach the full output of the following command from your project directory:
[output.txt](https://github.com/user-attachments/files/17282468/output.txt)

```toml
[dependencies]
opencv = { version = "0.93.1", features = ["clang-runtime"] }

```

Thank you for your help!
