### ISSUE TITLE
Install failing on no cuda even without cuda features in Cargo.toml

### ISSUE THREAD

**Issue by bread-mountain4** [twistedfall/opencv-rust#652]
I am wanting to install the library w/o cuda support as I do not need it for this specific usage.

My Cargo.toml
```toml
[package]
name = "testopencv"
version = "0.1.0"
edition = "2024"

[dependencies]
opencv = {version = "0.94", features = ["imgproc", "photo", "video", "videoio"]}
```

1. Linux 6.13.5-arch1-1 SMP PREEMPT_DYNAMIC
2. The way you installed OpenCV: arch linux package manager
3. OpenCV version: 4.11.0
4. rustc version: rustc 1.85.0 (4d91de4e4 2025-02-17)
5. Attach the full output of the following command from your project directory:
[out.txt](https://github.com/user-attachments/files/19142224/out.txt)

Had to attach the output as a file, but I think the relevant error is:
```
/build-script-build" "/usr/include/opencv4" "/home/me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/opencv-0.94.2/src_cpp" "/home/me/testopencv/target/debug/build/opencv-68c089f0c8295ed1/out" "cudaoptflow" ""
[opencv 0.94.2] === WARNING: 1 diagnostic messages
[opencv 0.94.2] ===    /usr/include/opencv4/opencv2/cudalegacy/NCV.hpp:52:10: fatal error: 'cuda_runtime.h' file not found
[opencv 0.94.2] 
[opencv 0.94.2] thread 'main' panicked at /home/me/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/opencv-binding-generator-0.95.0/src/generator.rs:416:17:
[opencv 0.94.2] === Errors during header parsing
```
